name: Build Android APK

on:
  push:
    branches: [ fix-app-issues ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties
        
      - name: Create google-services.json
        run: |
          mkdir -p app/src/main
          cat > app/google-services.json << 'EOL'
          {
            "project_info": {
              "project_number": "123456789012",
              "project_id": "localmarket-app",
              "storage_bucket": "localmarket-app.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789012:android:abcdef1234567890",
                  "android_client_info": {
                    "package_name": "com.localmarket.app"
                  }
                },
                "oauth_client": [
                  {
                    "client_id": "123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com",
                    "client_type": 1,
                    "android_info": {
                      "package_name": "com.localmarket.app",
                      "certificate_hash": "1234567890abcdef1234567890abcdef12345678"
                    }
                  },
                  {
                    "client_id": "123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com",
                    "client_type": 3
                  }
                ],
                "api_key": [
                  {
                    "current_key": "AIzaSyDummyKeyForLocalMarketApp12345"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": [
                      {
                        "client_id": "123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com",
                        "client_type": 3
                      }
                    ]
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOL
          
      - name: Create network_security_config.xml
        run: |
          mkdir -p app/src/main/res/xml
          cat > app/src/main/res/xml/network_security_config.xml << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <network-security-config>
              <base-config cleartextTrafficPermitted="false">
                  <trust-anchors>
                      <certificates src="system" />
                  </trust-anchors>
              </base-config>
              <domain-config cleartextTrafficPermitted="true">
                  <domain includeSubdomains="true">api.localmarket.com</domain>
                  <domain includeSubdomains="true">localhost</domain>
                  <domain includeSubdomains="true">10.0.2.2</domain>
              </domain-config>
          </network-security-config>
          EOL
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/debug/app-debug.apk
          token: ${{ github.token }}